imports:
    - { resource: easyadmin/ }

easy_admin:
    design:
        menu:
            -
                label: 'Address'
                priority: 4
                roles: ['ROLE_ADDRESS']
                children:
                    - { entity: 'Country', icon: 'globe' }
                    - { entity: 'Nationality', icon: 'flag-o' }
