services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $apiKey: '%krg_address.google_maps.api_key%'
            $locale: '%locale%'
            $country: '%krg_address.google_maps.country%'
            $libraries: ['places']

    KRG\AddressBundle\Form\Type\:
        resource: '../../Form/Type'
        public: true
        tags:
            - { name: form.type }

    KRG\AddressBundle\Helper\:
        resource: '../../Helper'
