services:
    krg.address.form.google_place:
        class: KRG\AddressBundle\Form\Type\GooglePlaceType
        arguments: ['@krg.address.ivory_google_map.helper.api', '%krg_address.google_maps.api_key%', '%locale%']
        tags:
            - { name: form.type, alias: google_place }

    krg.address.form.address:
        class: KRG\AddressBundle\Form\Type\AddressType
        arguments: ['@doctrine.orm.entity_manager']
        calls:
            - [setCountry, ['%krg_address.google_maps.country%']]
        tags:
            - { name: form.type, alias: address }

    krg.address.ivory_google_map.helper.api:
        class: KRG\AddressBundle\Ivory\GoogleMap\Helper\ApiHelper
        arguments: ['%krg_address.google_maps.api_key%', ['places'], '%locale%']
        public: false
