services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $apiKey: '%krg_address.google_maps.api_key%'
            $locale: '%locale%'
            $countries: '%krg_address.google_maps.countries%'
            $libraries: ['places']

    KRG\AddressBundle\Form\:
        resource: '../../Form'
        public: true
        tags:
            - { name: form.type }

    KRG\AddressBundle\Helper\:
        resource: '../../Helper'

    KRG\AddressBundle\Form:
