services:
    KRG\AddressBundle\Form\Type\GooglePlaceType:
        class: KRG\AddressBundle\Form\Type\GooglePlaceType
        arguments: ['@KRG\AddressBundle\Helper\ApiHelper', '%krg_address.google_maps.api_key%', '%locale%']
        tags:
            - { name: form.type, alias: google_place }

    KRG\AddressBundle\Form\Type\AddressType:
        class: KRG\AddressBundle\Form\Type\AddressType
        arguments: ['@doctrine.orm.entity_manager']
        calls:
            - [setCountry, ['%krg_address.google_maps.country%']]
        tags:
            - { name: form.type, alias: address }

    KRG\AddressBundle\Helper\ApiHelper:
        class: KRG\AddressBundle\Helper\ApiHelper
        arguments: ['%krg_address.google_maps.api_key%', ['places'], '%locale%']
        public: false
