services:
    KRG\AddressBundle\Helper\ApiHelper:
        - '%krg_address.google_maps.api_key%'
        - ['places']
        - '%locale%'

    KRG\AddressBundle\Form\Type\GooglePlaceType:
        autowire: true
        tags: [form.type]

    KRG\AddressBundle\Form\Type\AddressType:
        autowire: true
        tags: [form.type]
