easy_admin:
    entities:
        Country:
            class: 'KRG\AddressBundle\Entity\CountryInterface'
            list:
                fields:
                    - { property: 'name' }
                    - { property: 'code' }
                    - { property: 'prefered' }
                    - { property: 'active' }
                sort: ['name', 'ASC']
            form:
                fields:
                    - { type: 'group' }
                    - { property: 'name' }
                    - { property: 'code' }
                    - { property: 'flag' }
                    - { property: 'nationality' }
                    - { type: 'group' }
                    - { property: 'prefered' }
                    - { property: 'active' }
                    - { property: 'code' }
